### ISSUE TITLE
Left is Right.

### ISSUE THREAD

**Issue by 3phase33** [jzgdev/Push2UserModeScript#1]
self._mixer.set_select_buttons(self._ctrl_map[TRACKLEFT], self._ctrl_map[TRACKRIGHT])
These i had to swap.

**Comment by jzgdev** [comment]
Would you mind forking the repo and adding the changes? Would be great to have help developing this/turn it into a community thing

**Comment by jzgdev** [comment]
Nvm, will test now. But in the future just fork the repo, switch to the `develop` branch, add and commit whatever changes, and then do a pull request back here. I know the script needs work I'm just busy working on music most of the time.

**Comment by 3phase33** [comment]
Sorry. I wasn’t aware that I had to do this

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jzgdev** [comment]
You don't have to, just helpful. The whole point of github, for me anyways, is the open source aspect of everything. Particularly in midi/music development it's all very community oriented/developed and when users find a bug and know how to fix it, it helps much more to just fix it and integrate it back into this master repo than for me to have to go through and change/test everything myself. I don't actually know python, I'm just a stubborn producer who likes to experiment with sounds, gadgets, and code sometimes.

**Comment by 3phase33** [comment]
All good same as me. I don’t really know much python I just experiment with different parts of different scripts to get my devices to do what I need/want them to

Sent from my iPhone

On 20 Dec 2019, at 04:19, jzgdev <notifications@github.com<mailto:notifications@github.com>> wrote:


You don't have to, just helpful. The whole point of github, for me anyways, is the open source aspect of everything. Particularly in midi/music development it's all very community oriented/developed and when users find a bug and know how to fix it, it helps much more to just fix it and integrate it back into this master repo than for me to have to go through and change/test everything myself. I don't actually know python, I'm just a stubborn producer who likes to experiment with sounds, gadgets, and code sometimes.

**Comment by jzgdev** [comment]
I appreciate you figuring that out either way, definitely never noticed that issue. If there are any other changes you ever make just clone this repo and make them there and submit a pull request and if they work I'll happily integrate into this repo :)
